FROM node:13-alpine as coquin

RUN apk --no-cache add openssh-client git bash vim
RUN npm i npm@6.13 -g
RUN npm i @vue/cli@4.0.5 -g
RUN npm cache clean --force

ENTRYPOINT ["/bin/bash"]
WORKDIR /coquin
EXPOSE 8080 8080
